PremiumizemeAPIKey: xxxxxxxxx
Arrs:
- Name: ""
  URL: http://127.0.0.1:8989
  APIKey: xxxxxxxxx
  Type: Sonarr
- Name: ""
  URL: http://127.0.0.1:7878
  APIKey: xxxxxxxxx
  Type: Radarr
- Name: ""
  URL: http://127.0.0.1:8686
  APIKey: xxxxxxxxx
  Type: Lidarr
BlackholeDirectory: ""
PollBlackholeDirectory: false
PollBlackholeIntervalMinutes: 10
DownloadsDirectory: ""
TransferDirectory: ""
bindIP: 0.0.0.0
bindPort: "8182"
WebRoot: ""
SimultaneousDownloads: 5
DownloadSpeedLimit: 100
EnableTlsCheck: false
TransferOnlyMode: false
ArrHistoryUpdateIntervalSeconds: 20
